name: Bug
description: Incidencia o error
title: "BUG — "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descripción
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Resultado esperado
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Resultado actual
    validations:
      required: true
